global using System.Net;
global using Application;
global using Application.Interfaces;
global using Carter;
global using Infrastructure;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.AspNetCore.Mvc;
global using Newtonsoft.Json;
global using Presentation;
global using Presentation.Components;
global using ValidationResult = System.ComponentModel.DataAnnotations.ValidationResult;
global using _Imports = Presentation.Client._Imports;
