global using Application.DTO;
global using Application.Interfaces;
global using Domain.Entities;
global using Infrastructure.Database;
global using Infrastructure.Database.Configuration;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
