name: Build and Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"

  workflow_dispatch:

jobs:
  buildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest
    environment:
      name: GITHUBSECRETS  # This is defined in github.com/kinojoin settings

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore
        
      - name: Install CSharpier
        run: dotnet tool restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        env:
          TestDatabaseConnection: ${{ secrets.TESTDATABASECONNECTION }}
          MonkeyConnection: ${{ secrets.MONKEYCONNECTION }}
          PostgresConnection: ${{ secrets.POSTGRESCONNECTION }}
        run: dotnet test --filter FullyQualifiedName!~Test.Monkey
      
      - name: Validate Formatting
        run: dotnet csharpier --check .